// Date: 8/13/2016 5:43:15 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package finiteskies.fsmod.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;

public class ModelEntityMusketBullet extends ModelBase
{
  //fields
    ModelRenderer inner;
    ModelRenderer bottom;
    ModelRenderer top;
    ModelRenderer B;
    ModelRenderer F;
    ModelRenderer L;
    ModelRenderer R;
    
  
  public ModelEntityMusketBullet()
  {
    textureWidth = 32;
    textureHeight = 32;
    
    inner = new ModelRenderer(this, 0, 0);
	inner.addBox(0F, 0F, 0F, 1, 1, 1, 0F);
	inner.setRotationPoint(0F, 0F, 0F);
	inner.rotateAngleX = 0F;
	inner.rotateAngleY = 0F;
	inner.rotateAngleZ = 0F;
	inner.mirror = false;
	bottom = new ModelRenderer(this, 0, 0);
	bottom.addBox(0F, 0F, 0F, 1, 1, 1, 0F);
	bottom.setRotationPoint(0F, 1F, 0F);
	bottom.rotateAngleX = 0F;
	bottom.rotateAngleY = 0F;
	bottom.rotateAngleZ = 0F;
	bottom.mirror = false;
	top = new ModelRenderer(this, 0, 0);
	top.addBox(0F, 0F, 0F, 1, 1, 1, 0F);
	top.setRotationPoint(0F, -1F, 0F);
	top.rotateAngleX = 0F;
	top.rotateAngleY = 0F;
	top.rotateAngleZ = 0F;
	top.mirror = false;
	B = new ModelRenderer(this, 0, 0);
	B.addBox(0F, 0F, 0F, 1, 1, 1, 0F);
	B.setRotationPoint(0F, 0F, 1F);
	B.rotateAngleX = 0F;
	B.rotateAngleY = 0F;
	B.rotateAngleZ = 0F;
	B.mirror = false;
	F = new ModelRenderer(this, 0, 0);
	F.addBox(0F, 0F, 0F, 1, 1, 1, 0F);
	F.setRotationPoint(0F, 0F, -1F);
	F.rotateAngleX = 0F;
	F.rotateAngleY = 0F;
	F.rotateAngleZ = 0F;
	F.mirror = false;
	L = new ModelRenderer(this, 0, 0);
	L.addBox(0F, 0F, 0F, 1, 1, 1, 0F);
	L.setRotationPoint(1F, 0F, 0F);
	L.rotateAngleX = 0F;
	L.rotateAngleY = 0F;
	L.rotateAngleZ = 0F;
	L.mirror = false;
	R = new ModelRenderer(this, 0, 0);
	R.addBox(0F, 0F, 0F, 1, 1, 1, 0F);
	R.setRotationPoint(-1F, 0F, 0F);
	R.rotateAngleX = 0F;
	R.rotateAngleY = 0F;
	R.rotateAngleZ = 0F;
	R.mirror = false;
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float scale)
  {
	    super.render(entity, f, f1, f2, f3, f4, scale);
	    setRotationAngles(f, f1, f2, f3, f4, scale, entity);
		inner.render(scale);
		bottom.render(scale);
		top.render(scale);
		B.render(scale);
		F.render(scale);
		L.render(scale);
		R.render(scale);
		System.out.println("################################################################################################ Render MusketBullet");
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}


